version: "3.1"

services:
  postgres:
    image: postgres:9.5-alpine
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=user
      - POSTGRES_DB=todolist
    ports:
      - "5432:5432"
